# Generated by Django 2.0.4 on 2019-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11)),
                ('pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
