# Generated by Django 2.0.4 on 2019-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
