# Generated by Django 2.0.4 on 2019-04-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190421_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
