# Generated by Django 2.0.4 on 2019-04-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.CharField(default='/img/3.jpg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.CharField(default='/img/default_profile2.jpg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(default='这个人很懒，什么都没写...', max_length=50, null=True),
        ),
    ]
