# Generated by Django 2.0.4 on 2019-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190421_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='figure',
            field=models.ImageField(null=True, upload_to='user_portraits'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.CharField(default='static/img/3.jpg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.CharField(default='static/img/default_profile2.jpg', max_length=50, null=True),
        ),
    ]
