# Generated by Django 2.0.4 on 2019-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190424_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='figure',
            field=models.ImageField(default='/static/img/default_profile.jpg', null=True, upload_to='user_figures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.CharField(default='static/img/default_profile.jpg', max_length=50, null=True),
        ),
    ]
