# Generated by Django 2.0.4 on 2019-04-24 16:42

from django.db import migrations, models
import myapp.tool


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190424_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='figure',
            field=models.ImageField(default='/media/user_figures/default_profile.jpg', null=True, storage=myapp.tool.FigureImageStorage, upload_to='user_figures'),
        ),
    ]
