# Generated by Django 2.0.4 on 2019-05-06 17:41

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('category', models.IntegerField(choices=[(0, '生活'), (1, '人像'), (2, '风景'), (3, '自拍'), (4, '旅游'), (5, '美食'), (6, '纪实')], default=0)),
                ('note', models.CharField(max_length=100, null=True)),
                ('favour', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('data', models.ImageField(upload_to=myapp.models.user_photo_directory)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Album')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='portrait',
        ),
        migrations.AlterField(
            model_name='user',
            name='figure',
            field=models.ImageField(default='/user_figures/default_profile.jpg', null=True, upload_to='user_figures'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
