# Generated by Django 2.0.4 on 2019-05-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190507_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Favour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='favour',
        ),
        migrations.AddField(
            model_name='photo',
            name='cover',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.IntegerField(choices=[(0, '生活'), (1, '人像'), (2, '插画'), (3, '自拍'), (4, '素描'), (5, '美食'), (6, '纪实'), (7, '风景')], default=0),
        ),
        migrations.AddField(
            model_name='favour',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Album'),
        ),
        migrations.AddField(
            model_name='favour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Album'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='albumcomment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Album'),
        ),
        migrations.AddField(
            model_name='albumcomment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.AlbumComment'),
        ),
    ]
