# Generated by Django 2.0.4 on 2019-05-08 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190508_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.IntegerField(choices=[(0, '生活'), (1, '人像'), (2, '插画'), (3, '二次元'), (4, '设计'), (5, '美食'), (6, '纪实'), (7, '风景')], default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
