# Generated by Django 2.0.4 on 2019-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20190509_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='figure',
            field=models.ImageField(default='/default_profile.jpg', null=True, upload_to='user_figures'),
        ),
    ]
